import type { CredentialRecord } from "@/lib/vc/types";

export function CertificateCanvas({ record, qrDataUrl }: { record: CredentialRecord; qrDataUrl: string }) {
  const subject = record.vc.credentialSubject;
  const date = new Date(record.issuedAt).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
  const status = record.status === "ACTIVE" || record.status === "ISSUED" ? "Issued & Permanent" : record.status;
  const did = record.issuerDid.length > 32 ? `${record.issuerDid.slice(0, 24)}...${record.issuerDid.slice(-8)}` : record.issuerDid;
  const specialization = typeof subject.credentialType === "string" && subject.credentialType !== record.credentialType ? subject.credentialType : undefined;
  return <div className="certificate-canvas" style={styles.canvas}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@500;600;700;800&family=Cormorant+Garamond:ital,wght@0,400;0,600;0,700;1,400;1,600&family=Inter:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,600;0,700;1,400&family=Pinyon+Script&display=swap');`}</style>
    <div style={styles.outer}><div style={styles.inner}>
      {[["top", "left"], ["top", "right"], ["bottom", "left"], ["bottom", "right"]].map(([v, h]) => <span key={`${v}${h}`} style={{ ...styles.corner, [v]: -2, [h]: -2 }} />)}
      <header style={styles.header}><div style={styles.logoBox}><img src={subject.institutionLogoUrl as string | undefined} alt="Institution crest" style={styles.logo} /></div><h1 style={styles.institution}>{subject.institution}</h1><p style={styles.charter}>ESTABLISHED BY STATE LEGISLATURE ACT</p></header>
      <section style={styles.body}><p style={styles.serifItalic}>This certifies that</p><h2 style={styles.holder}>{subject.holderName}</h2><div style={styles.nameRule}><i /><b /><i /></div><p style={styles.description}>has successfully completed the prescribed curriculum and fulfilled all academic requirements for the degree of</p><h3 style={styles.title}>{subject.title}</h3>{specialization && <p style={styles.specialization}>{specialization}</p>}</section>
      <div style={styles.divider}><span>◆</span></div>
      <footer style={styles.footer}><div style={styles.meta}><Meta label="Credential Identifier" value={record.credentialId} mono /><Meta label="Conferral Date" value={date} /><Meta label="Validity Status" value={status} status /></div><div style={styles.signature}><div style={styles.script}>Authorized Signatory</div><div style={styles.signatureLine} /><strong>AUTHORIZED SIGNATORY</strong><em>Vice-Chancellor / Registrar</em><small>▣ DID: {did} • Blockchain Cryptographic Proof</small></div><div style={styles.qrBlock}><div style={styles.qrFrame}><img src={qrDataUrl} alt="Scan to verify" style={styles.qr} /></div><div><strong>SCAN TO VERIFY</strong><p>Instant public registry ledger proof</p><b>● CRYPTOGRAPHICALLY SECURED</b></div></div></footer>
    </div><aside style={styles.platform}><span>AUTHENTIC DEGREE RECORD　•　INSTITUTIONAL SERIES 2024</span><span>Powered by　<strong>VIGYAN<i>.ID</i></strong></span></aside></div></div>;
}

function Meta({ label, value, mono, status }: { label: string; value: string; mono?: boolean; status?: boolean }) { return <div style={styles.metaItem}><label>{label}</label><span style={mono ? styles.mono : undefined}>{status ? `●  ${value}` : value}</span></div>; }

const styles: Record<string, any> = {
  canvas: { width: 1140, height: 807, boxSizing: "border-box", padding: 28, background: "#fcfcfb", color: "#172033", fontFamily: "Inter, sans-serif", backgroundImage: "radial-gradient(circle, rgba(200,16,46,.018), transparent 60%), repeating-radial-gradient(circle, rgba(23,32,51,.012) 0, rgba(23,32,51,.012) 1px, transparent 1px, transparent 18px)" },
  outer: { position: "relative", height: "100%", boxSizing: "border-box", border: "2px solid rgba(23,32,51,.8)", padding: 16 }, inner: { position: "relative", height: "100%", boxSizing: "border-box", border: "1px solid rgba(200,16,46,.6)", padding: "38px 48px 24px", display: "flex", flexDirection: "column", justifyContent: "space-between", background: "rgba(255,255,255,.4)" }, header: { textAlign: "center", display: "flex", flexDirection: "column", alignItems: "center" }, logoBox: { height: 64, marginBottom: 14 }, logo: { height: 64, width: "auto", objectFit: "contain" }, institution: { margin: 0, fontFamily: "Cinzel, serif", fontSize: 34, letterSpacing: ".14em", textTransform: "uppercase" }, charter: { margin: "4px 0 0", fontSize: 11, letterSpacing: ".25em", color: "#5b6472" }, body: { textAlign: "center", margin: "18px 0 10px" }, serifItalic: { fontFamily: "Cormorant Garamond, serif", fontStyle: "italic", fontSize: 21, color: "#5b6472", margin: "0 0 10px" }, holder: { margin: 0, fontFamily: "Cormorant Garamond, serif", fontSize: 42, textTransform: "uppercase", letterSpacing: ".08em" }, nameRule: { display: "flex", alignItems: "center", justifyContent: "center", gap: 12, margin: "12px auto 16px" }, nameRuleI: {}, description: { maxWidth: 690, margin: "0 auto 10px", fontFamily: "Cormorant Garamond, serif", fontStyle: "italic", fontSize: 18, lineHeight: 1.35, color: "#5b6472" }, title: { margin: 0, fontFamily: "Cinzel, serif", fontSize: 24, letterSpacing: ".08em", textTransform: "uppercase" }, specialization: { margin: "4px 0 0", color: "#c8102e", fontSize: 13, fontWeight: 600, letterSpacing: ".12em", textTransform: "uppercase" }, divider: { textAlign: "center", borderTop: "1px solid rgba(23,32,51,.15)", height: 1, margin: "4px auto 16px", width: "66%", color: "#c8102e" }, footer: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 28, alignItems: "end" }, meta: { borderLeft: "2px solid rgba(23,32,51,.1)", paddingLeft: 14 }, metaItem: { marginBottom: 7, fontSize: 12 }, metaItemLabel: {}, mono: { fontFamily: "monospace" }, signature: { textAlign: "center", display: "flex", flexDirection: "column", alignItems: "center" }, script: { fontFamily: "Pinyon Script, cursive", fontSize: 29, fontStyle: "italic" }, signatureLine: { width: 224, borderTop: "1.5px solid #172033", margin: "-2px 0 6px" }, qrBlock: { display: "flex", alignItems: "center", gap: 12, justifyContent: "flex-end" }, qrFrame: { padding: 4, border: "1px solid rgba(200,16,46,.3)", background: "white" }, qr: { width: 88, height: 88, display: "block" }, platform: { display: "flex", justifyContent: "space-between", fontSize: 10, color: "#5b6472", marginTop: 10 }, corner: { position: "absolute", width: 30, height: 30, borderTop: "2px solid #c8102e", borderLeft: "2px solid #c8102e" } };

styles.metaItem.label = { display: "block", fontSize: 9.5, letterSpacing: ".12em", color: "#5b6472", textTransform: "uppercase", fontWeight: 600 };
styles.signature["strong"] = { fontFamily: "Cinzel, serif", fontSize: 11, letterSpacing: ".12em" };
styles.signature["em"] = { fontFamily: "Cormorant Garamond, serif", fontSize: 12, color: "#5b6472" };
styles.signature["small"] = { marginTop: 12, fontFamily: "monospace", fontSize: 8.5, color: "rgba(91,100,114,.65)" };
styles.qrBlock["strong"] = { fontFamily: "Cinzel, serif", fontSize: 10, letterSpacing: ".12em" };
styles.qrBlock["p"] = { fontSize: 9, color: "#5b6472", margin: "3px 0" };
styles.qrBlock["b"] = { fontSize: 8, color: "#c8102e", letterSpacing: ".08em" };
styles.platform["strong"] = { color: "#172033", fontSize: 11 }; styles.platform["i"] = { color: "#c8102e", fontStyle: "normal" };
